### ISSUE TITLE
use on windows machine?

### ISSUE THREAD

**Issue by TylonHH** [TLINDEN/kleingebaeck#3]
Hello,
can I use this also on a windows maschine? I installed "make" and also perl with pod2text but I get
```C:\kleingebaeck-main>make install
Das System kann den angegebenen Pfad nicht finden.
#CGO_LDFLAGS='-static' go build -tags osusergo,netgo -ldflags "-extldflags=-static" -o kleingebaeck
Der Befehl "#CGO_LDFLAGS" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
make: *** [Makefile:44: buildlocal] Error 1```

**Comment by TLINDEN** [comment]
Hi,

you don't need to build the tool from source :) There are readily built versions for a number of platforms available. Just go to the [latest release](https://github.com/TLINDEN/kleingebaeck/releases/latest) page and download the version apropriate for you:

![klreleases](https://github.com/TLINDEN/kleingebaeck/assets/1322812/52c93881-2827-4031-8a67-db001a21a761)

So, in your case that would be: [kleingebaeck-windows-amd64-0.0.4](https://github.com/TLINDEN/kleingebaeck/releases/download/v0.0.4/kleingebaeck-windows-amd64-0.0.4). Just copy the binary to a proper location, open a cmd window and start using it.

Also, you don't need to create a configuration file. Just find out your kleinanzeigen.de user-id and provide it using the `-u` parameter. The output directory can also be specified on the commandline using the `-o` flag.

Please be aware of issue https://github.com/TLINDEN/kleingebaeck/issues/4 though. The tool might not work correctly on windows because of this, and I don't have a windows system to test it. So, eventually try again a couple days later when I fixed the above bug and try the next release.

**Comment by TLINDEN** [comment]
Update:

I made a new release with the two issues #4 and #5 fixed: [0.0.5](https://github.com/TLINDEN/kleingebaeck/releases/tag/v0.0.5). There's now an exe file for windows available for direct download: [kleingebaeck-windows-amd64-0.0.5.exe](https://github.com/TLINDEN/kleingebaeck/releases/download/v0.0.5/kleingebaeck-windows-amd64-0.0.5.exe).

If you have other problems on windows, please open a new issue.


best regards,
Tom

**Comment by TLINDEN** [comment]
PS: I made another release which fixes more portability issues on Wndows: [0.0.5}(https://github.com/TLINDEN/kleingebaeck/releases/latest)

**Comment by TylonHH** [comment]
as you also figured out since 0.0.6 has some bugs, I tried 0.0.5
There it was possible to get the ads. I recognizes that in one ad with 11 different pictures, one picture was 8 times backuped and other pictures are missing. I just wanna let you know.

**Comment by TLINDEN** [comment]
Hi, according to my tests it seems to work now on windows, could you please be so kind and test it as well?

Prerelease is here: https://github.com/TLINDEN/kleingebaeck/releases/tag/v0.1.0-BETA

Thanks!

**Comment by TylonHH** [comment]
> Hi, according to my tests it seems to work now on windows, could you please be so kind and test it as well?
> 
> Prerelease is here: https://github.com/TLINDEN/kleingebaeck/releases/tag/v0.1.0-BETA

Test was succesful. Even all the picture were included.

Klasse
