### ISSUE TITLE
689 ads but only 524 folders in output dir?

### ISSUE THREAD

**Issue by Heart1010** [TLINDEN/kleingebaeck#70]
**Description**
First let me say thank you very much (!) for this amazing app!!!

I did a first test and it worked - I have many folders in my output dir but what I don't understand is the difference from the script output
```bash
> .\kleingebaeck-windows-amd64-0.3.3.exe -u 127291161 -o "Backup"
Successfully downloaded 689 ads with 4154 images to Backup
```
`689` is correct - this is also shown on the kleinanzeigen site

![image](https://github.com/TLINDEN/kleingebaeck/assets/1481680/c6bd01c6-efc4-4e64-ba81-39c5d0055c9a)

But I only have `524` folders in my Backup folder - shouldn't it also be 689 folders?

**Comment by TLINDEN** [comment]
Hi,

that's indeed weird. I'll take a look at it, although this might take some time, since these are really LOTS of ads.

But meanwhile could you please re-run it with the -d option, redirect the output into a file (though I don't know how to do that on windows, maybe the terminal app has some log option), put the output into a gist.github.com and post the link?

Also are you able to determine which ads are missing and a link to one of them here? 

And, while you're at it, is it possible to download one of those ads directly (leave the -u param and just supply the ad url)?

That would certainly help a lot.

Tom

**Comment by TLINDEN** [comment]
Ok, I looked at the issue.

The problem is that you have a couple of ads with duplicate names:

![Screenshot_20240209-215154_JuiceSSH](https://github.com/TLINDEN/kleingebaeck/assets/1322812/5467dabb-70f8-49a3-9b91-111b22f20cd9)

So you could try to create a file anzeigen.conf in the sam dir where you run the tool with the following content:

```toml
adnametemplate = "{{.Slug}}-{{.ID}}"
```

and run kleingebäck with the option `-c anzeigen.conf`.

This will add the ad id to the directory names. That way duplicate ad titles will be written into different dirs anyway.

**Comment by Heart1010** [comment]
Perfect, with the `adnametemplate =  "{{.Slug}}-{{.ID}}"` it worked 👍 

P.S.: Is it possible to use such a variable also for the outdir?
Let's say I want to add the current date to the folder name, something like:
`outdir = "Backup_{{.DATE}}"` (e.g. Backup_2024-02-09)

**Comment by TLINDEN** [comment]
I'll see into it. New issue created for this.

**Comment by TLINDEN** [comment]
Hi,

as of release v0.3.4 the output directory can be templated as well, refer to the [documentation](https://github.com/TLINDEN/kleingebaeck/blob/main/kleingebaeck.pod#output-dir-template) on how to do this.

**Comment by Heart1010** [comment]
> Hi,
> 
> as of release v0.3.4 the output directory can be templated as well, refer to the [documentation](https://github.com/TLINDEN/kleingebaeck/blob/main/kleingebaeck.pod#output-dir-template) on how to do this.

Tested the new v0.3.4 version with an account which has 0 active ads at the moment - here kleingebaeck generates an output dir with no content. Would it make sense in such constellation (where 0 ads are found) to don't generate the output dir at all?
